"""Normalized action catalog for the standalone web simulator."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class WebActionSpec(BaseModel):
    """One normalized web action that can be rendered directly in the UI."""

    action_key: str
    agent_name: str
    room: str
    service: str
    label: str
    description: str
    params: dict[str, Any] = Field(default_factory=dict)
    env_targets: list[str] = Field(default_factory=list)


def _room_targets(room: str, *variables: str) -> list[str]:
    return [f"{room}_{variable}" for variable in variables]


def _spec(
    *,
    action_key: str,
    agent_name: str,
    room: str,
    service: str,
    label: str,
    description: str,
    params: dict[str, Any],
    env_targets: list[str],
) -> WebActionSpec:
    return WebActionSpec(
        action_key=action_key,
        agent_name=agent_name,
        room=room,
        service=service,
        label=label,
        description=description,
        params=params,
        env_targets=env_targets,
    )


WEB_ACTION_SPECS: tuple[WebActionSpec, ...] = (
    _spec(
        action_key="air_conditioner.living.cool_24",
        agent_name="air_conditioner_agent",
        room="living",
        service="set_profile",
        label="Living Cool 24C",
        description="Enable cooling in the living room with a balanced target temperature.",
        params={"power": True, "mode": "cool", "target_temp": 24, "fan_level": "medium"},
        env_targets=_room_targets("living", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.living.heat_22",
        agent_name="air_conditioner_agent",
        room="living",
        service="set_profile",
        label="Living Heat 22C",
        description="Enable heating in the living room with a gentle warm target.",
        params={"power": True, "mode": "heat", "target_temp": 22, "fan_level": "medium"},
        env_targets=_room_targets("living", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.living.dry",
        agent_name="air_conditioner_agent",
        room="living",
        service="set_profile",
        label="Living Dry Mode",
        description="Run the living-room air conditioner in dry mode.",
        params={"power": True, "mode": "dry", "target_temp": 25, "fan_level": "low"},
        env_targets=_room_targets("living", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.living.off",
        agent_name="air_conditioner_agent",
        room="living",
        service="turn_off",
        label="Living AC Off",
        description="Turn off the living-room air conditioner.",
        params={"power": False},
        env_targets=_room_targets("living", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.bedroom.cool_24",
        agent_name="air_conditioner_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Cool 24C",
        description="Enable cooling in the bedroom with a balanced target temperature.",
        params={"power": True, "mode": "cool", "target_temp": 24, "fan_level": "medium"},
        env_targets=_room_targets("bedroom", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.bedroom.heat_22",
        agent_name="air_conditioner_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Heat 22C",
        description="Enable heating in the bedroom with a gentle warm target.",
        params={"power": True, "mode": "heat", "target_temp": 22, "fan_level": "medium"},
        env_targets=_room_targets("bedroom", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.bedroom.dry",
        agent_name="air_conditioner_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Dry Mode",
        description="Run the bedroom air conditioner in dry mode.",
        params={"power": True, "mode": "dry", "target_temp": 25, "fan_level": "low"},
        env_targets=_room_targets("bedroom", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="air_conditioner.bedroom.off",
        agent_name="air_conditioner_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom AC Off",
        description="Turn off the bedroom air conditioner.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="window.living.open",
        agent_name="window_agent",
        room="living",
        service="set_position",
        label="Living Window Open",
        description="Open the living-room window fully for ventilation and daylight.",
        params={"position": "open"},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="window.living.half",
        agent_name="window_agent",
        room="living",
        service="set_position",
        label="Living Window Half",
        description="Open the living-room window halfway.",
        params={"position": "half"},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="window.living.closed",
        agent_name="window_agent",
        room="living",
        service="set_position",
        label="Living Window Closed",
        description="Close the living-room window.",
        params={"position": "closed"},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="window.bedroom.open",
        agent_name="window_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Window Open",
        description="Open the bedroom window fully for ventilation and daylight.",
        params={"position": "open"},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="window.bedroom.half",
        agent_name="window_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Window Half",
        description="Open the bedroom window halfway.",
        params={"position": "half"},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="window.bedroom.closed",
        agent_name="window_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Window Closed",
        description="Close the bedroom window.",
        params={"position": "closed"},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "brightness"),
    ),
    _spec(
        action_key="curtain.living.open",
        agent_name="curtain_agent",
        room="living",
        service="set_position",
        label="Living Curtain Open",
        description="Open the living-room curtain for natural light.",
        params={"position": "open"},
        env_targets=_room_targets("living", "brightness", "temp"),
    ),
    _spec(
        action_key="curtain.living.half",
        agent_name="curtain_agent",
        room="living",
        service="set_position",
        label="Living Curtain Half",
        description="Set the living-room curtain to a balanced half-open position.",
        params={"position": "half"},
        env_targets=_room_targets("living", "brightness", "temp"),
    ),
    _spec(
        action_key="curtain.living.closed",
        agent_name="curtain_agent",
        room="living",
        service="set_position",
        label="Living Curtain Closed",
        description="Close the living-room curtain for shade.",
        params={"position": "closed"},
        env_targets=_room_targets("living", "brightness", "temp"),
    ),
    _spec(
        action_key="curtain.bedroom.open",
        agent_name="curtain_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Curtain Open",
        description="Open the bedroom curtain for natural light.",
        params={"position": "open"},
        env_targets=_room_targets("bedroom", "brightness", "temp"),
    ),
    _spec(
        action_key="curtain.bedroom.half",
        agent_name="curtain_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Curtain Half",
        description="Set the bedroom curtain to a balanced half-open position.",
        params={"position": "half"},
        env_targets=_room_targets("bedroom", "brightness", "temp"),
    ),
    _spec(
        action_key="curtain.bedroom.closed",
        agent_name="curtain_agent",
        room="bedroom",
        service="set_position",
        label="Bedroom Curtain Closed",
        description="Close the bedroom curtain for shade.",
        params={"position": "closed"},
        env_targets=_room_targets("bedroom", "brightness", "temp"),
    ),
    _spec(
        action_key="fan.living.high",
        agent_name="fan_agent",
        room="living",
        service="set_profile",
        label="Living Fan High",
        description="Run the living-room fan at high speed.",
        params={"power": True, "speed": "high"},
        env_targets=_room_targets("living", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fan.living.low",
        agent_name="fan_agent",
        room="living",
        service="set_profile",
        label="Living Fan Low",
        description="Run the living-room fan at low speed.",
        params={"power": True, "speed": "low"},
        env_targets=_room_targets("living", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fan.living.off",
        agent_name="fan_agent",
        room="living",
        service="turn_off",
        label="Living Fan Off",
        description="Turn off the living-room fan.",
        params={"power": False},
        env_targets=_room_targets("living", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fan.bedroom.high",
        agent_name="fan_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Fan High",
        description="Run the bedroom fan at high speed.",
        params={"power": True, "speed": "high"},
        env_targets=_room_targets("bedroom", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fan.bedroom.low",
        agent_name="fan_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Fan Low",
        description="Run the bedroom fan at low speed.",
        params={"power": True, "speed": "low"},
        env_targets=_room_targets("bedroom", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fan.bedroom.off",
        agent_name="fan_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom Fan Off",
        description="Turn off the bedroom fan.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "temp", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.living.high",
        agent_name="fresh_air_agent",
        room="living",
        service="set_profile",
        label="Living Fresh Air High",
        description="Run strong fresh-air exchange in the living room.",
        params={"power": True, "flow_level": "high"},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.living.low",
        agent_name="fresh_air_agent",
        room="living",
        service="set_profile",
        label="Living Fresh Air Low",
        description="Run gentle fresh-air exchange in the living room.",
        params={"power": True, "flow_level": "low"},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.living.off",
        agent_name="fresh_air_agent",
        room="living",
        service="turn_off",
        label="Living Fresh Air Off",
        description="Turn off the living-room fresh-air system.",
        params={"power": False},
        env_targets=_room_targets("living", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.bedroom.high",
        agent_name="fresh_air_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Fresh Air High",
        description="Run strong fresh-air exchange in the bedroom.",
        params={"power": True, "flow_level": "high"},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.bedroom.low",
        agent_name="fresh_air_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Fresh Air Low",
        description="Run gentle fresh-air exchange in the bedroom.",
        params={"power": True, "flow_level": "low"},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="fresh_air.bedroom.off",
        agent_name="fresh_air_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom Fresh Air Off",
        description="Turn off the bedroom fresh-air system.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "air", "temp", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.living.45",
        agent_name="dehumidifier_agent",
        room="living",
        service="set_profile",
        label="Living Dehumidify 45%",
        description="Run the living-room dehumidifier toward a drier 45 percent target.",
        params={"power": True, "target_humidity": 45, "level": "high"},
        env_targets=_room_targets("living", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.living.50",
        agent_name="dehumidifier_agent",
        room="living",
        service="set_profile",
        label="Living Dehumidify 50%",
        description="Run the living-room dehumidifier toward a balanced 50 percent target.",
        params={"power": True, "target_humidity": 50, "level": "medium"},
        env_targets=_room_targets("living", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.living.off",
        agent_name="dehumidifier_agent",
        room="living",
        service="turn_off",
        label="Living Dehumidifier Off",
        description="Turn off the living-room dehumidifier.",
        params={"power": False},
        env_targets=_room_targets("living", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.bedroom.45",
        agent_name="dehumidifier_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Dehumidify 45%",
        description="Run the bedroom dehumidifier toward a drier 45 percent target.",
        params={"power": True, "target_humidity": 45, "level": "high"},
        env_targets=_room_targets("bedroom", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.bedroom.50",
        agent_name="dehumidifier_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Dehumidify 50%",
        description="Run the bedroom dehumidifier toward a balanced 50 percent target.",
        params={"power": True, "target_humidity": 50, "level": "medium"},
        env_targets=_room_targets("bedroom", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="dehumidifier.bedroom.off",
        agent_name="dehumidifier_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom Dehumidifier Off",
        description="Turn off the bedroom dehumidifier.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "humidity", "noise", "energy"),
    ),
    _spec(
        action_key="lighting.living.focus",
        agent_name="lighting_agent",
        room="living",
        service="set_profile",
        label="Living Focus Light",
        description="Turn on bright task lighting in the living room.",
        params={"power": True, "brightness": 78, "scene": "focus"},
        env_targets=_room_targets("living", "brightness", "energy"),
    ),
    _spec(
        action_key="lighting.living.cozy",
        agent_name="lighting_agent",
        room="living",
        service="set_profile",
        label="Living Cozy Light",
        description="Turn on softer cozy lighting in the living room.",
        params={"power": True, "brightness": 34, "scene": "cozy"},
        env_targets=_room_targets("living", "brightness", "energy"),
    ),
    _spec(
        action_key="lighting.living.off",
        agent_name="lighting_agent",
        room="living",
        service="turn_off",
        label="Living Lights Off",
        description="Turn off the living-room lights.",
        params={"power": False},
        env_targets=_room_targets("living", "brightness", "energy"),
    ),
    _spec(
        action_key="lighting.bedroom.focus",
        agent_name="lighting_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Focus Light",
        description="Turn on bright task lighting in the bedroom.",
        params={"power": True, "brightness": 74, "scene": "focus"},
        env_targets=_room_targets("bedroom", "brightness", "energy"),
    ),
    _spec(
        action_key="lighting.bedroom.cozy",
        agent_name="lighting_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Cozy Light",
        description="Turn on softer cozy lighting in the bedroom.",
        params={"power": True, "brightness": 30, "scene": "cozy"},
        env_targets=_room_targets("bedroom", "brightness", "energy"),
    ),
    _spec(
        action_key="lighting.bedroom.off",
        agent_name="lighting_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom Lights Off",
        description="Turn off the bedroom lights.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "brightness", "energy"),
    ),
    _spec(
        action_key="computer.living.music",
        agent_name="computer_agent",
        room="living",
        service="set_profile",
        label="Living Music",
        description="Start music playback on the living-room computer.",
        params={"power": True, "activity": "music", "volume": 46, "screen_brightness": 24},
        env_targets=_room_targets("living", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.living.video",
        agent_name="computer_agent",
        room="living",
        service="set_profile",
        label="Living Video",
        description="Start video playback on the living-room computer.",
        params={"power": True, "activity": "video", "volume": 38, "screen_brightness": 66},
        env_targets=_room_targets("living", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.living.idle",
        agent_name="computer_agent",
        room="living",
        service="set_profile",
        label="Living Computer Idle",
        description="Keep the living-room computer on but idle.",
        params={"power": True, "activity": "idle", "volume": 0, "screen_brightness": 18},
        env_targets=_room_targets("living", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.living.off",
        agent_name="computer_agent",
        room="living",
        service="turn_off",
        label="Living Computer Off",
        description="Turn off the living-room computer.",
        params={"power": False},
        env_targets=_room_targets("living", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.bedroom.music",
        agent_name="computer_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Music",
        description="Start music playback on the bedroom computer.",
        params={"power": True, "activity": "music", "volume": 34, "screen_brightness": 18},
        env_targets=_room_targets("bedroom", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.bedroom.video",
        agent_name="computer_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Video",
        description="Start video playback on the bedroom computer.",
        params={"power": True, "activity": "video", "volume": 28, "screen_brightness": 58},
        env_targets=_room_targets("bedroom", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.bedroom.idle",
        agent_name="computer_agent",
        room="bedroom",
        service="set_profile",
        label="Bedroom Computer Idle",
        description="Keep the bedroom computer on but idle.",
        params={"power": True, "activity": "idle", "volume": 0, "screen_brightness": 14},
        env_targets=_room_targets("bedroom", "noise", "brightness", "energy", "temp"),
    ),
    _spec(
        action_key="computer.bedroom.off",
        agent_name="computer_agent",
        room="bedroom",
        service="turn_off",
        label="Bedroom Computer Off",
        description="Turn off the bedroom computer.",
        params={"power": False},
        env_targets=_room_targets("bedroom", "noise", "brightness", "energy", "temp"),
    ),
)

WEB_ACTION_INDEX: dict[str, WebActionSpec] = {
    spec.action_key: spec for spec in WEB_ACTION_SPECS
}


def list_web_actions() -> list[WebActionSpec]:
    """Return the full web action catalog."""

    return list(WEB_ACTION_SPECS)


def get_web_action(action_key: str) -> WebActionSpec:
    """Return one action spec by key."""

    try:
        return WEB_ACTION_INDEX[action_key]
    except KeyError as exc:
        raise KeyError(f"Unknown web action: {action_key}") from exc
